# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 22:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0002_auto_20170125_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lastname',
            new_name='alias',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='firstname',
            new_name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(default=datetime.datetime(2017, 1, 30, 22, 33, 14, 125960)),
        ),
    ]
